version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: "03:00"
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: "03:00"
    open-pull-requests-limit: 10
